ALTER TABLE "UserRankHistory" ADD COLUMN "streakParticipationAt" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "UserRankHistory" ADD COLUMN "streakAbsenceAt" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "UserRankHistory" ADD COLUMN "streakWithinTopAt" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "UserRankHistory" ADD COLUMN "streakFlyingAt" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "UserRankHistory" ADD COLUMN "protectCoolTime" INTEGER NOT NULL DEFAULT 0;
