name = "midnight-network-frontend"
compatibility_date = "2025-12-16"
routes = [
	{ pattern = "<host>/*", zone_name = "<host>" }
]

[observability]
enabled = true

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
