// SPDX-FileCopyrightText: 2026 Secineralyr
// SPDX-License-Identifier: AGPL-3.0-or-later

// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import { listLocalDatabases } from '@prisma/adapter-d1';
import { defineConfig } from 'prisma/config';

export default defineConfig({
	schema: 'prisma/',
	migrations: {
		path: 'prisma/migrations',
	},
	datasource: {
		url: `file:${listLocalDatabases().pop()}`,
	},
});
