name = "midnight-network-backend"
main = "src/index.ts"
compatibility_date = "2025-11-17"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[triggers]
crons = ["1 15 * * *", "59 14 * * *"]

[[kv_namespaces]]
binding = "SESSION"
id = "REPLACE_ME"

[[kv_namespaces]]
binding = "CACHE"
id = "REPLACE_ME"

[[d1_databases]]
binding = "DB"
database_name = "midnight-network"
database_id = "REPLACE_ME"
migrations_dir = "./prisma/migrations"

[vars]
ENVIRONMENT = "production"
GAME_JOIN_POST_TEXT_REGEX = ""
TARGET_MATCH_HOUR = 15
TARGET_MATCH_MINUTES = 0
POST_MATCH_RESULT_TITLE = ""
POST_MATCH_RESULT_URL = "https://{host}/"
POST_MATCH_RESULT_TEMPLATE = "{title}\n\n{ranks}\n\n有効記録数：{valid}\nフライング記録数：{flying}\n\n{url}"
DISABLE_POST_MATCH_RESULT = false
POST_MATCH_REMIND_TEXT = ""
DISABLE_WEBHOOK_BEFORE_TARGET_MATCH = 60000
DISABLE_WEBHOOK_AFTER_TARGET_MATCH = 60000

[vars.crons]
CRON_DAILY = "1 15 * * *"
CRON_DAILY_REMIND = "59 14 * * *"
