name = "midnight-network-backend"
main = "src/index.ts"
compatibility_date = "2025-12-16"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[triggers]
crons = ["0 * * * *"]

[[kv_namespaces]]
binding = "SESSION_KV"
id = "REPLACE_ME"
preview_id = "REPLACE_ME"

[[d1_databases]]
binding = "DB"
database_name = "midnight-network"
database_id = "REPLACE_ME"
migrations_dir = "../entity/prisma/migrations"

[vars]
MK_HOST = "<host>"
API_TOKEN = "<token?>"
WEB_HOST = "test.midnight.network.local"
BOT_USER_NAME = "username"
DISABLE_USER_NAME = ["username"]
GAME_JOIN_POST_TEXT_REGEX = ""
TARGET_MATCH_HOUR = 0
TARGET_MATCH_MINUTES = 0
POST_MATCH_RESULT_TITLE = ""
POST_MATCH_REMIND_TEXT = ""
DISABLE_WEBHOOK_BEFORE_TARGET_MATCH = 60000
DISABLE_WEBHOOK_AFTER_TARGET_MATCH = 60000
